### ISSUE TITLE
Javascript client

### ISSUE THREAD

**Issue by GiggleLiu** [Jugsaw/Jugsaw#21]
## Pipeline for requesting demos
```mermaid
graph TD;
    REQ[HTTP Request]
    IR[Jugsaw IR]
    ADT[Objects as Tree]
    JSON[Standard JSON object]
    REQ --> IR;
    IR --> |Lark| ADT;
    ADT --> JSON;
```

## Pipeline for sending requests
```mermaid
graph TD;
    ADT[Call as a Tree];
    IR[Jugsaw IR];
    CALL[Call Request];
    FETCH[Fetch Request];
    FRONT[IR -> Tree -> JSON -> frontend];
    ADT --> IR;
    IR --> CALL;
    CALL --> job_id;
    job_id --> FETCH;
    FETCH --> FRONT
```

## TODOs
 - [x] error handling,
 - [x] adt construction from input args and kwargs.
 - [x] html app display.
 - [x] transforming app to a more readable form.
 - [x] register JS to a JS server.
 - [x] live serving html

**Comment by GiggleLiu** [comment]
One can access the "registered" javascript with
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/Jugsaw/Jugsaw/src/js/jugsawirparser.js"></script>
```
